version: '3'

volumes:
  pgdata:

services:
  django:
    image: dyjo/digitalocean-apps-django
    environment:
      - "POSTGRES_USER"
      - "POSTGRES_PASSWORD"
      - "DJANGO_SUPERUSER_USERNAME"
      - "DJANGO_SUPERUSER_PASSWORD"
      - "DJANGO_SUPERUSER_EMAIL"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13
    environment:
      - "POSTGRES_USER"
      - "POSTGRES_PASSWORD"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django"]
    volumes:
      - pgdata:/var/lib/postgresql/data
